<a href="https://colab.research.google.com/github/abubakirovx/ai-foundation/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("student_performance.csv")
print("Dataset shape (rows,columns) :",df.shape)
print("Column name :",df.columns.tolist())

print("First 5 rows of Dataset :")
print(df.head())

print("Summary statistics :")
print(df.describe())

print("Data types and null info:")
print(df.info())

Dataset shape (rows,columns) : (1000000, 6)
Column name : ['student_id', 'weekly_self_study_hours', 'attendance_percentage', 'class_participation', 'total_score', 'grade']
First 5 rows of Dataset :
   student_id  weekly_self_study_hours  attendance_percentage  \
0           1                     18.5                   95.6
1           2                     14.0                   80.0
2           3                     19.5                   86.3
3           4                     25.7                   70.2
4           5                     13.4                   81.9

   class_participation  total_score grade
0                  3.8         97.9     A
1                  2.5         83.9     B
2                  5.3        100.0     A
3                  7.0        100.0     A
4                  6.9         92.0     A
Summary statistics :
           student_id  weekly_self_study_hours  attendance_percentage  \
count  1000000.000000           1000000.000000         1000000.000000
mean    500000.500000                15.029127              84.711046
std     288675.278933                 6.899431               9.424143
min          1.000000                 0.000000              50.000000
25%     250000.750000                10.300000              78.300000
50%     500000.500000                15.000000              85.000000
75%     750000.250000                19.700000              91.800000
max    1000000.000000                40.000000             100.000000

       class_participation     total_score
count       1000000.000000  1000000.000000
mean              5.985203       84.283845
std               1.956421       15.432969
min               0.000000        9.400000
25%               4.700000       73.900000
50%               6.000000       87.500000
75%               7.300000      100.000000
max              10.000000      100.000000
Data types and null info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 6 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   student_id               1000000 non-null  int64
 1   weekly_self_study_hours  1000000 non-null  float64
 2   attendance_percentage    1000000 non-null  float64
 3   class_participation      1000000 non-null  float64
 4   total_score              1000000 non-null  float64
 5   grade                    1000000 non-null  object
dtypes: float64(4), int64(1), object(1)
memory usage: 45.8+ MB
None

In [9]:
print("Avarage scores by columns")
df[["class_participation","total_score"]].mean()

Avarage scores by columns

class_participation     5.985203
total_score            84.283845
dtype: float64

In [10]:
print("Maximum scores by columns")
df[["class_participation","total_score"]].max()

Maximum scores by columns

class_participation     10.0
total_score            100.0
dtype: float64

In [11]:
print("Minimum scores by columns")
df[["class_participation","total_score"]].min()

Minimum scores by columns

class_participation    0.0
total_score            9.4
dtype: float64

In [12]:
# Correlation
df[["class_participation","total_score"]].corr()

                     class_participation  total_score
class_participation             1.000000     0.000684
total_score                     0.000684     1.000000

In [21]:
df["total sum"]=df[["class_participation","total_score"]].sum(axis=1)
df["avarage score"]=df['total sum']/2
df["passed"]=np.where(df['avarage score']>=50 ,"Yes","No")

print(df[['total sum',"avarage score","passed"]].head())

   total sum  avarage score passed
0      101.7          50.85    Yes
1       86.4          43.20     No
2      105.3          52.65    Yes
3      107.0          53.50    Yes
4       98.9          49.45     No

In [25]:
weekly_self_study_group=df.groupby("weekly_self_study_hours")[["class_participation","total_score"]].mean()
print(weekly_self_study_group)

attendance_percentage_group=df.groupby("attendance_percentage")[["class_participation","total_score"]].mean()
print(attendance_percentage_group)

pass_rate = df["passed"].value_counts(normalize=True)*100
print("pass_rate\n",pass_rate)

                         class_participation  total_score
weekly_self_study_hours
0.0                                 6.004802    50.109975
0.1                                 6.057515    49.791871
0.2                                 6.037842    50.770370
0.3                                 5.974810    50.623976
0.4                                 5.924363    50.665764
...                                      ...          ...
39.6                                6.266667   100.000000
39.7                                5.377778   100.000000
39.8                                6.200000   100.000000
39.9                                6.520000   100.000000
40.0                                6.253012   100.000000

[401 rows x 2 columns]
                       class_participation  total_score
attendance_percentage
50.0                              6.094583    84.925000
50.1                              6.000000    82.544444
50.2                              5.377778    82.766667
50.3                              6.990000    86.200000
50.4                              5.880000    91.760000
...                                    ...          ...
99.6                              5.944599    84.719051
99.7                              6.060689    84.449785
99.8                              5.995231    83.840954
99.9                              5.898655    83.955531
100.0                             5.984458    84.275568

[501 rows x 2 columns]
pass_rate
 passed
No     62.5741
Yes    37.4259
Name: proportion, dtype: float64

In [33]:
# Convert scores to Numpy array
scores = df[["class_participation","total_score"]].values

# Mean ,Std Deviation
print("Numpy Mean",np.mean(scores,axis=0))
print("Numpy Std",np.std(scores,axis=0))

# Z-score (normalize)
z_score= scores-np.mean(scores,axis=0)/np.std(scores,axis=0)
print("Z-score (normalized numbers)\n",z_score)
#Avarage 0
#Negative -
#Positive +

Numpy Mean [ 5.9852026 84.2838453]
Numpy Std [ 1.95641953 15.43296106]
Z-score (normalized numbers)
 [[ 0.74073663 92.43871198]
 [-0.55926337 78.43871198]
 [ 2.24073663 94.53871198]
 ...
 [ 2.74073663 82.43871198]
 [ 2.24073663 94.53871198]
 [ 1.04073663 94.53871198]]

In [49]:
#How many students score above 90 avarage?
top_scores= df[df['avarage score']>=55]
print("Students score above 90 avarage,",len(top_scores))

#How many students failed exam?
failed= df[df['passed']=="No"]
print("Students failed exam,",len(failed))

Students score above 90 avarage, 6591
Students failed exam, 625741